### ISSUE TITLE
Feature Request for UA client to optionally provide PPA credentials rather than directly configure the PPA

### ISSUE THREAD

**Issue by mdscunningham** [canonical/ubuntu-pro-client#1139]
As the previously generated credentials method for configuring ESM has been deprecated (in preference of using the UA client to retrieve and configure necessary apt credentials) there is no convenient way for clients to lookup their ESM or other PPA credentials. This is desirable for those clients that are looking to create local apt mirrors for ESM and/or other PPAs.

For clients that want to set up a local mirror, either using Landscape On-Prem or other means, they still need to have the necessary apt credentials to do this. As it currently stands, this means that clients have to: have a machine with sufficient network access, where the UA client can successfully setup the PPA and credentials; then also know where those credentials are configured (/etc/apt/auth.conf.d/); then also retrieve those credentials from the configuration created by the UA Client.

It would therefore seem reasonable to have an option for the UA client to just print the apt credentials for use by clients that want to set up a local apt mirror for that PPA. I would argue that this would be a useful quality of life improvement to the UA client, providing more usefulness and transparency for clients. While this request is specifically for ESM at this time, this could be expanded to other PPAs that may be enabled or configured by the UA client in the future (FIPS, CIS, CC, etc).

**Comment by mitechie** [comment]
Do you have a sample set of instructions that folks might use for this? Ideally, we'd look at how that workflow is set up and fit well into that process. We'd want to see exactly what information they need. Is it just the credential? Should it be the entire apt resource lines? Should it even just be a conf file you can drop on the mirror host? 

It's a bit special in that only the mirror admin needs this vs all users of the client and it might even fit better on the token web page to help that user vs building into the client itself? e.g. on https://ubuntu.com/advantage

**Comment by mdscunningham** [comment]
In both cases regarding ESM that I mention, all that is needed is the credentials (user and password), but for example:

Landscape:
```
gpg --keyserver keyserver.ubuntu.com --recv 56F7650A24C9E9ECF87C4D8D4067E40313CB4B13
gpg -a --export 56F7650A24C9E9ECF87C4D8D4067E40313CB4B13 > esm-trusty-mirror-key.asc
landscape-api import-gpg-key esm-trusty-mirror-key esm-trusty-mirror-key.asc
landscape-api create-distribution ubuntu
landscape-api create-series \
  --pockets security,updates \
  --components main \
  --architectures amd64,i386 \
  --mirror-gpg-key esm-trusty-mirror-key \
  --gpg-key mirror-key \
  --mirror-uri https://<ESM_USER_NAME>:<ESM_PASSWORD>@esm.ubuntu.com/ubuntu \
  --mirror-series trusty esm ubuntu
landscape-api sync-mirror-pocket security esm ubuntu
```

APT Mirror:
In theory, the configured `/etc/apt/auth.conf.d/90ubuntu-advantage` could just be copied from whichever machine the UA Client was run on. However, the case could be made to either print the credentials or the configuration, for use on another machine. That other machine either may not have sufficient network access for the UA Client to work (firewall restrictions, or otherwise air-gapped environment), or may not have the UA Client installed to perform these configuration actions.

**Comment by lucasmoura** [comment]
We already have a way for users to properly configure airgapped machines. Therefore, I don't think the requested feature is still necessary.

What do you think @renanrodrigo @orndorffgrant ?

**Comment by orndorffgrant** [comment]
@mdscunningham are the airgapped instructions and accompanying scripts sufficient enough that we can close this issue?

**Comment by mdscunningham** [comment]
Yeah, this is probably fine to close. The air-gapped solution makes some assumptions that don't really work for Landscape mirrors, but that's a separate discussion. This request was mostly a "nice to have" anyway. 

Our documentation around mirroring ESM stuff in Landscape instructs the user to get the credentials from the `/etc/apt/auth.conf.d/90ubuntu-advantage` file after attaching the client and enabling ESM. We also don't get a lot of cases regarding this, so no pressing need for this feature at this time.

**Comment by orndorffgrant** [comment]
Thanks @mdscunningham! I think we'll go ahead and close this issue then. Let us know if you have any related issues or feature requests.

**Comment by ajkuck** [comment]
@mdscunningham I stumbled across this issue trying to configure my own airgapped landscape environment.

You've referred to "existing instructions" in your comments.  Could you include a link to them?  Specifically the portions where you obtain the ESM_USER_NAME, ESM_PASSWORD you referenced.

I've found plenty of documentation for configuring other aspects of landscape, but nothing that supplies those type of credentials.

**Comment by mdscunningham** [comment]
@ajkuck the existing documentation around setting up an ESM mirror within self-hosted Landscape are in the Canonical KB
https://portal.support.canonical.com/ua/s/article/How-to-mirror-the-Ubuntu-ESM-repositories-using-Landscape-On-Premises

Basically after enabling ESM using the Pro client, the credentials for these authenticated repositories are configured in this apt configuration: `/etc/apt/auth.conf.d/90ubuntu-advantage`

You then use the username and password in the URL when setting up the mirror in Landscape, the mirror url will then look something like this:

`https://bearer:<auth-token>@esm.ubuntu.com/...`
