### ISSUE TITLE
FIPS update pin priority is not working as expected

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-pro-client#1248]
When enabling `fips-updates` on xenial, we can see that the pin priority we are expecting is incorrect:

 ```
 500 https://esm.staging.ubuntu.com/fips-updates/ubuntu xenial-updates/main amd64 Packages
     release v=16.04,o=UbuntuFIPS,a=xenial-updates,n=xenial,l=UbuntuFIPS,c=main,b=amd64
     origin esm.staging.ubuntu.com
```

We would expect the priority to be `1001` as it occurs when we enable `fips`.

This issue may be causing an upgrade issue from xenial to bionic, where we remove the `ubuntu-fips` metapackage during the `do-release-upgrade` operation and do not install the bionic version of it for `fips-updates`.

**Comment by renanrodrigo** [comment]
As I am revisiting the FIPS details I stumbled upon this one, and it seems invalid:
```
```

**Comment by renanrodrigo** [comment]
Executed an upgrade and it works fine, including the pinning.
