### ISSUE TITLE
testing/linting: integration tests should validate the ua-tools deb install succeeds without apt errors

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#1306]
during image creation for integration tests. if there are bugs in debian/* scripts apt will raise an error on the CLI. BDD tests should be check for any pkg install errors and raise them if there are problems.

**Comment by orndorffgrant** [comment]
Tracking in SC-927

**Comment by orndorffgrant** [comment]
Today, the first step of our integration tests will fail if the package fails to install.
