### ISSUE TITLE
auto-attach: no need to grab lock if auto-attach is a noop.

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#1391]
Ubuntu PRO images run `ua auto-attach` per boot and exit 0 and noop if there is no new instance-id in instance metadata.
ua auto-attach subcommand grabs a lockfile and retries 3 times if it collides with another lock holder. auto-attach should be smarter and only try to grab the lock if it knows it needs to perform work. 

Not retrying will avoid a number of LockHeldError traceback messages in logs.

**Comment by orndorffgrant** [comment]
Tracking in SC-925

**Comment by orndorffgrant** [comment]
@lucasmoura @renanrodrigo @blackboxsw auto-attach no longer re-attaches on instance-id change and the systemd unit has a `ConditionPathExists=!/var/lib/ubuntu-advantage/private/machine-token.json` so I don't think we need to do any further optimization here. I'll go ahead and close this, but feel free to re-open if you disagree.
