### ISSUE TITLE
ua client doesn't support pointing at mirror repos

### ISSUE THREAD

**Issue by mitechie** [canonical/ubuntu-pro-client#1406]
If a customer uses landscape to mirror the esm repositories the ua client should be able to attach and be instructed to use the mirrors for apt access vs the primary internet based options.

**Comment by orndorffgrant** [comment]
Tracking in SC-891

**Comment by cpaelzer** [comment]
There is an effort to support air-gapped environments which will include pointing at internal mirrors.
Hence i'm replacing the tracking issue to: SC-1013

**Comment by lucasmoura** [comment]
We now have supported for an airgapped configuration of the Pro client. Due to that, I am now closing this issue
