### ISSUE TITLE
Azure: 5 min wait between retries of snap install canonical-livepatch

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#1426]
From deployment logs  I can see a gap of 5 mins between exit 0 of snap.seeded and eventual `snap install canonical-livepatch`

and a very prolonged setup of ua auto-attach
```bash
$ systemd-analyze blame
    5min 15.842s ua-auto-attach.service

# logs
2021-03-03 19:24:37,455 - util.py:(488) [DEBUG]: Ran cmd: /usr/bin/snap wait system seed.loaded, rc: 0 stderr: b''
....
2021-03-03 19:29:29,573 - util.py:(488) [DEBUG]: Ran cmd: /usr/bin/snap install canonical-livepatch, rc: 0 stderr: b''
```

I think uaclient.util.subp in `uaclient.entitlements.livepatch` might need to actually supply a sensible imeout to avoid prologed initial timeout when retries are set.

**Comment by orndorffgrant** [comment]
Tracking in SC-848

**Comment by orndorffgrant** [comment]
@renanrodrigo just checked and this isn't currently happening - we're seeing auto-attaches of around 30 seconds and consider that acceptable for now. If extended delays happen again we can re-open.
