### ISSUE TITLE
fix: log commands run on the user's behalf

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#1477]
right now fix short-circuits the uaclient/cli.py logic which logs the user-provided commands on the commandline. When 'ua attach <token>' or 'ua enable <service>' is run. Make sure we are logging all configuration changes performed on the system.

**Comment by orndorffgrant** [comment]
Tracking in SC-822

**Comment by orndorffgrant** [comment]
This is fixed in the current version.
