### ISSUE TITLE
d/postinst: rename keyrings/ubuntu-advantage-esm-infra-trusty.gpg to keyrings/ubuntu-advantage-esm-infra.gpg

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#1539]
minor postinst nit. Since keyrings/ubuntu-advantage-esm-infra.gpg is actually a keyring valid for all Ubuntu releases, let's rename that file in postinst dropping the "-trusty" suffix.

Ensure upgrade from previously attached Trusty Xenial systems migrates the old artifact if it exists to the new filename. Adjust esm key name definitions in the uaclient/entitlements/esm.py

**Comment by orndorffgrant** [comment]
Tracking in SC-758

**Comment by renanrodrigo** [comment]
actually renaming the key to `ubuntu-pro-esm-infra.gpg` to standardize them all
