### ISSUE TITLE
When contract is expired but not enforced, ua adds confusing apt messages.

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-pro-client#1575]
In the scenario where the ua contract is expired, but not yet enforced by the back-end, we print messages that look like the following on an `apt upgrade`:
```
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'apt autoremove' to remove it.

*Your UA Apps: ESM subscription has EXPIRED*
Enabling UA Apps: ESM service would provide security updates for following
packages:
  libkrb5-3 libgssapi-krb5-2 libk5crypto3 krb5-locales libkrb5support0
5 esm-apps security updates NOT APPLIED. Renew your UA services at
https://ubuntu.com/advantage

*Your UA Infra: ESM subscription has EXPIRED*
Enable UA Infra: ESM to receive additional future security updates.

See https://ubuntu.com/esm or run: sudo ua status

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

The following packages will be upgraded:
  apt-transport-https krb5-locales libapt-inst2.0 libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0
7 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
5 esm-apps security updates
Need to get 3459 kB of archives.
After this operation, 26.6 kB disk space will be freed.
Do you want to continue? [Y/n]
```

Notice that at the top we claim that the esm-apps updates will not be applied, then at the bottom, apt says that they will be applied.

We should either adjust the messaging here or ensure that the service disabling happens in tighter concert with the messaging to avoid this scenario.

**Comment by orndorffgrant** [comment]
Tracking in SC-668

**Comment by lucasmoura** [comment]
@orndorffgrant I think we can close this issue right ? After the messaging refactor we performed, I think this issue is no longer valid

**Comment by orndorffgrant** [comment]
@lucasmoura Yes I agree. Our messages are better now than they were, and I have an item this cycle to re-consider the contract expiration experience in general, so I don't think we need this issue anymore.
