### ISSUE TITLE
Bionic upgrade 17 -> 27.0~18.04.1 triggers warning

### ISSUE THREAD

**Issue by cpaelzer** [canonical/ubuntu-pro-client#1591]
This is low prio as it is non-fatal, but worth to be aware and to eventually be fixed.

On upgrade in Bionic from v17 to the one of the staging PPA I've got

```
Preconfiguring packages ...
(Reading database ... 68930 files and directories currently installed.)
Preparing to unpack .../ubuntu-advantage-tools_27.0~18.04.1_ppc64el.deb ...
Unpacking ubuntu-advantage-tools (27.0~18.04.1) over (17) ...
dpkg: warning: unable to delete old directory '/var/cache/ubuntu-advantage-tools': Directory not empty
Setting up ubuntu-advantage-tools (27.0~18.04.1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/ua-reboot-cmds.service → /lib/systemd/system/ua-reboot-cmds.service.
Created symlink /etc/systemd/system/timers.target.wants/ua-messaging.timer → /lib/systemd/system/ua-messaging.timer.
Removing obsolete conffile /etc/update-motd.d/80-esm ...
Removing obsolete conffile /etc/update-motd.d/80-livepatch ...
Removing obsolete conffile /etc/cron.daily/ubuntu-advantage-tools ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
```

Afterwards `/var/cache/ubuntu-advantage-tools` isn't present, so something deleted it eventually.
Therefore I can't check what was "in there" before the upgrade.
The base system was Bionic-GA as deployed by MAAS (on ppc64)

**Comment by orndorffgrant** [comment]
Tracking in SC-636

**Comment by cpaelzer** [comment]
Time has catched up, people would for years supposed to install from the point releases that have newer versions.
Furthermore soon Bionic is in extended support, that means it will stay great but probably even less installed.
Close this for not being imporant.
