### ISSUE TITLE
airgap registration

### ISSUE THREAD

**Issue by patrizio-bassi** [canonical/ubuntu-pro-client#2226]
Currently ua client can register/activate only terminating on the canonical public portal which requires a internet connection.

It would be good to support a airgapped environment by terminating the procedure on locally installed landscape server, where purchased licenses are loaded.

is it in the roadmap?
Thank you

**Comment by orndorffgrant** [comment]
I'm really sorry for the lack of updates here @patrizio-bassi. The short version is: Yes this is supported, but you'll want to reach out to [Customer Support](https://ubuntu.com/support) to help you get set up. We're about to publish a documentation page on this subject which will include a little more information but going through Customer Support is the recommendation.
That new documentation page will land in #2705 and will close this issue.
