### ISSUE TITLE
"pro status" is monochrome before being attached

### ISSUE THREAD

**Issue by cpaelzer** [canonical/ubuntu-pro-client#2283]
I'm fine if this is as it should be, but I wanted to ask to be sure.

Is it intentional that the "Available Yes" is just normal console color.
While the "Entitled Yes" that replaces it after an attach is in friendly green?

**Comment by orndorffgrant** [comment]
Tracking in SC-1336

**Comment by renanrodrigo** [comment]
Keep in mind the guidelines say colors should only be there if someone asks for it :|
https://discourse.ubuntu.com/t/use-of-colours/18880

**Comment by renanrodrigo** [comment]
This is a duplicate (or rather, a subset) of #1418 which will be solved as part of the current UX redesign.
