### ISSUE TITLE
No easy way to check if machine is attached

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-pro-client#2328]
Today, there is no easy way for an user to programmatically verify that the machine is attached to a Pro subscription. To do that, the user would need to call `pro status --format json` and parse the output for the `attached` field to verify that it is attached or not.

**Comment by orndorffgrant** [comment]
Tracking in SC-1340

**Comment by lucasmoura** [comment]
We now have an API endpoint that checks is a machine is attached or not:
https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/references/api/#u-pro-status-is-attached-v1

Because of that, I am closing this issue
