### ISSUE TITLE
security-status suggests to check something without useful info

### ISSUE THREAD

**Issue by cpaelzer** [canonical/ubuntu-pro-client#2443]
Example from today on jammy with pro attached:

```
$ pro security-status --esm-apps
...
Package names in bold currently have an available update
with 'esm-apps' enabled
Packages:
imagemagick-6-common imagemagick-6.q16 libimage-magick-perl
libimage-magick-q16-perl libjs-jquery-ui libmagick++-6.q16-8
libmagickcore-6.q16-6 libmagickcore-6.q16-6-extra libmagickwand-6.q16-6
libopenexr25 3270-common aapt abi-compliance-checker abi-dumper abootimg
adequate androguard android-framework-res android-libaapt android-libandroidfw
android-libbacktrace android-libbase android-libcutils android-liblog
android-libunwind android-libutils android-libziparchive apcalc apksigner
apktool apt-btrfs-snapshot apt-file apt-rdepends arch-test arj ark audacious
audacious-plugins audacious-plugins-data audacity audacity-data augeas-lenses
...
wkhtmltopdf wodim x3270 xclip xdelta xdelta3 xfonts-x3270-misc xmlbeans
xmlstarlet xmlto xorriso xsane xsane-common xterm xvfb zbarcam-gtk
ttf-mscorefonts-installer ubuntu-restricted-addons ubuntu-restricted-extras
unrar

For example, run:
    apt-cache policy libwireshark15
to learn more about that package.
```

**Problem**
Random selected packages suggested to be checked with apt-cache policy.
The output on that is not telling me anything.

```
$ apt-cache policy libwireshark15
libwireshark15:
  Installed: 3.6.2-2
  Candidate: 3.6.2-2
  Version table:
 *** 3.6.2-2 500
        500 http://de.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

Neither did it have an outstanding esm update, nor a past one applied that would be interesting to learn about.
I'd suggest we should handle that in this order:
a) If there are packages with an existing, but not applied update - show the hint for one of these
b) If there are no (a), then if there are packages with esm updates applied, show the hint for one of these
c) If there are no (a) and no (b), there is nothing great to hint at in regard to apt-cache policy - in that case do print that hint at all please

**Comment by renanrodrigo** [comment]
Tracking in SC-1470

**Comment by renanrodrigo** [comment]
a) b) and c) are valid points, and changing `apt policy` for `apt show` will actually give information on the packages themselves instead of pointing to origins and such
