### ISSUE TITLE
Please mention apt_news in docs

### ISSUE THREAD

**Issue by cpaelzer** [canonical/ubuntu-pro-client#2444]
I know this is in an interim state changing from the in-code message (which directly printed how to deactivate it) to the server hosted message (which once available will again mention how to disable it) - and currently we are in between with the server not being ready and therefore no message being shown.

```
...
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'apt autoremove' to remove it.
#
# News about significant security updates, features and services will
# appear here to raise awareness and perhaps tease /r/Linux ;)
# Use 'pro config set apt_news=false' to hide this and future APT news.
#
The following packages will be upgraded:
...
```

But it will be back in a bit via [motd](https://bazaar.launchpad.net/~ubuntu-motd/ubuntu-motd/trunk/view/head:/aptnews.json), and future messages will not always show the hint how to disable which some users might search for.
I've checked https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/explanations/apt_messages.html and it did not mention apt_news messages at all.

I think the purpose (as written in the current message), the rough design (to not stall on it, to not fail if not reachable) and the way to enable/disable it (sudo pro config set apt_news=false|true) should be mentioned on that doc page.

P.S. I didn't find apt_news in the current docs nor in the open PRs, but I hope I didn't just miss it.

**Comment by cpaelzer** [comment]
Please also mention that this becomes a config in /etc/ubuntu-advantage/uaclient.conf as some might want to configure this via other means (some deployment script that can touch files but not run commands for example).

**Comment by orndorffgrant** [comment]
We now have documentation on enabling and disabling apt_news here: https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/howtoguides/disable_enable_apt_news.html

While the setting can technically go into `/etc/ubuntu-advantage/uaclient.conf`, that is a deprecated way to configure apt news, so we shouldn't document it/encourage it. The correct way is what is described in the how-to guide linked above.

I think what we have is no sufficient so I'm closing this issue. Feel free to re-open or submit a new issue if more detail about apt news is needed in the documentation.
