### ISSUE TITLE
tab completion sends a request to the contracts server with each press

### ISSUE THREAD

**Issue by Monochromics** [canonical/ubuntu-pro-client#2556]
This may not technically be an issue, but while testing the airgapped contracts server deployment, I noticed that every time you attempt a tab complete anything, a request is sent. 

The left side is the output of ua-airgapped, the right is a different vm pointing to this contracts server via a client.conf modification.

![image](https://user-images.githubusercontent.com/27440437/232551422-20f230f9-1423-42af-ad0f-d2db73d5b18a.png)

This feels unnecessary and is likely contributing to the slow tab-completion observed in the client.

Feel free to close if this is intended behavior.

**Comment by orndorffgrant** [comment]
Thank you for reporting this!

Definitely not intended behavior :upside_down_face: 

We haven't given our tab completion much attention lately - we'll take a look at this for the next release.
