### ISSUE TITLE
pro is not in my installation

### ISSUE THREAD

**Issue by w0nd3rer** [canonical/ubuntu-pro-client#2571]
*Please describe the question or issue you're facing with "Get started with Ubuntu Pro Client - Ubuntu Pro Client documentation".*

---
*Reported from: https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/tutorials/basic_commands.html*

**Comment by orndorffgrant** [comment]
Hello @w0nd3rer! Thanks for reaching out. Are you saying that the `pro` command is not found when you try to run it?
For context: the command used to be called `ua`; `pro` was added as an alias in late 2022.
To help us figure out the problem can you answer these questions:
- What version of Ubuntu are you using?
- Is your installation up to date? If not please run `sudo apt-get update && sudo apt-get upgrade` and let me know if you still don't have the `pro` command.

**Comment by w0nd3rer** [comment]
Grant,
I apologize for wasting your time.  Not sure how I did it but i pulled the
14.04.6 version.  Just pulled the 22.04.2 and will install it.
Thanks,
Bob
