### ISSUE TITLE
Improve the default error message when  uncaught exceptions happen

### ISSUE THREAD

**Issue by renanrodrigo** [canonical/ubuntu-pro-client#2600]
user logs should be in the local `.cache` dir instead - we should reflect that in the messaging.

## How to reproduce:
force an error for a command
run it as non-root
```
$ pro security-status
Unexpected error(s) occurred.
For more details, see the log: /var/log/ubuntu-advantage.log
To file a bug run: ubuntu-bug ubuntu-advantage-tools
```

**Comment by a-dubs** [comment]
For clarification, should the error message be adaptable so that when the message is detected as being run as non-root, it changes the log location in the message accordingly?
@orndorffgrant

**Comment by orndorffgrant** [comment]
@a-dubs yes that would be great!
