### ISSUE TITLE
docs: tutorial includes old status output that doesn't include esm-apps

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-pro-client#2627]
*Please describe the question or issue you're facing with "Get started with Ubuntu Pro Client - Ubuntu Pro Client documentation".*

https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/tutorials/basic_commands.html doesn't mention esm-apps anywhere. If you follow the tutorial today, you'll see esm-apps, but the example output in the tutorial doesn't show it.

---
*Reported from: https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/tutorials/basic_commands.html*

**Comment by s-makin** [comment]
Addressed [via this PR](https://github.com/canonical/ubuntu-pro-client/pull/2639)
