### ISSUE TITLE
Token still active in Dashboard after building Docker container: How to properly detach?

### ISSUE THREAD

**Issue by martinkoehler** [canonical/ubuntu-pro-client#2659]
*Please describe the question or issue you're facing with "How to enable Ubuntu Pro Services in a Dockerfile - Ubuntu Pro Client documentation".*
This works fine. I noted that using a free personal token immediately shows up in the ubuntu pro Dashboard.
However since there is no `pro detach` this does not free the token after the container was built?!
Even doing a  `pro detach --assume-yes` from the command line in a pro enabled package does not release the token, although the system reports that the system was actually detached.

Is this different in the paid version and how do I handle "spend" tokens, that are "invalid"? 

---
*Reported from: https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/howtoguides/enable_in_dockerfile.html*

**Comment by orndorffgrant** [comment]
Thank you for the feedback @martinkoehler!

To answer your question right away here: The dashboard shows a count of machines active within the last 24 hours. When you `pro detach` or when you uninstall `ubuntu-advantage-tools` (as the docker how-to-guide suggests), then the machine becomes inactive. After the machine is inactive for 24 hours, the count in the dashboard will decrement. For that reason, you don't need to worry about the dashboard count going up during the build, and you don't need to worry about the dashboard count going above your limit temporarily.

We should add an explanation page about this @s-makin and link to it from the docker how-to-guide, at least.

**Comment by martinkoehler** [comment]
Thanks a lot. This helps and works exactly as described.
Please allow a follow up:

For various reasons, my container will run approx. a month before it is replaced by a new version. In the container "supervisor" controls apache2 and cron and unattended-update is installed. During the LTS phase this ensured that the container got daily updates.
Of course following the reciept above, this no longer works. since de-installing ubuntu-advantage-tools during the docker build detaches the machine from pro (which is intended)
If I want to attach and update during the runtime, of the container I can 

a) re-install ubuntu-advantage-tools
b) issue "pro attach <token>" or better use the Docker-compose secret
c) Do "apt update && apt upgrade"

However, since every new image will have a new machine-id I expect that this eats up my tokens. I can of course `apt remove ubuntu-advantage-tools` as d), but this seems strange. 
`pro detach` might also work, but this gave my an error in Docker when executed manually (`system not started with systemd`) and I was not sure this really detaches?!
`pro status` showed that it detached by the way.

So my question is: 
What would be the best procedure here? 
Does it help if I mount the hosts `/etc/machine-id` and `/var/lib/dbus/machine-id`  into the container before attaching? 
... and would this use the same license even for new images? 
Would it be possible to omit the detaching in this scenario?

I hesitate to implement d), since the container might be killed before d) by loading a new image and then the license probably can't be detached anymore?!
Any guidance would be greatly appreciated.

BTW: I know that this procedure is not "the way Docker is intended". It uses Docker as a "virtual machine", but this is a legacy app and using "real" virtual machines is unfortunately not an option. Neither is it possible to install this app in a later Ubuntu version :-(

**Comment by orndorffgrant** [comment]
Hello @martinkoehler I'm sorry for the delay in getting back to you.

If the containers are intended to run for a long time and receive pro updates while running, then the correct thing to do would be to follow the how-to-guide to set up pro, but leave `ubuntu-advantage-tools` installed and do **not** detach.

The downside is that there will be Pro auth secrets left in the docker image, but as long as you don't publish the images publicly, that is probably okay.

That also means that each container will increase the machine count in the dashboard. Assuming you're using a subscription purchased for physical machines and running these containers on physical machines that are running Ubuntu Pro, then you don't need to worry about the containers increasing your machine count in the dashboard. We keep track of which machines are physical vs virtual on the backend, so we will know they are containers. We plan to expose this information in the dashboard but it isn't there yet.

When you eventually de-provision the container, you don't need to worry about detach-ing either, as we will notice that the container is no longer active.

**Comment by martinkoehler** [comment]
Thanks. 
Issue can be closed
