### ISSUE TITLE
fips: pro-client should `apt full-upgrade` instead of hardcoding lists of packages to upgrade

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-pro-client#2667]
Our hardcoded list has missed packages in the past and will likely eventually miss something in the future. `apt full-upgrade` will upgrade all relevant packages to their fips versions.

**Comment by orndorffgrant** [comment]
Rather than a `full-upgrade`, we will loop through all installed packages and if they have a candidate from the fips repo, upgrade them.

Note that we still will need some logic to install -hmac variants of some packages.

**Comment by carlosbravoa** [comment]
will this work if the customer has installed a package that is newer than the one listed in the fips repo? For instance if I have openssl 3.0 installed, will it downgrade it?

**Comment by carlosbravoa** [comment]
FWIW. Went from FIPS to FIPS-updates and got the following kernel: `5.4.0-1021-aws-fips #21+fips2-Ubuntu`
After installation I had to reboot to boot with the new kernel and run an update/upgrade cycle.
I got a new kernel: `5.4.0-1108-aws-fips #116+fips1-Ubuntu`
So I had to reboot again.
The question is is it possible to get installed the latest kernel when enabling FIPS-updates?

**Comment by orndorffgrant** [comment]
> will this work if the customer has installed a package that is newer than the one listed in the fips repo?

Generally, yes. An example of this would be `shim-signed` which in some cases needs a lower version from the fips apt repo.

>  For instance if I have openssl 3.0 installed, will it downgrade it?

openssl major versions are special. If you install a major version of openssl that your Ubuntu release wasn't designed to use, then you're already in a unsupported state, and you should probably re-provision before enabling fips anyway.

Let's say you installed openssl3 (and therefore the `libssl3` package) on e.g. Focal from some non-Ubuntu source (Ubuntu doesn't provide openssl 3 for Focal), and then you ran `pro enable fips` with the solution proposed in comment #2 of this issue. Then the `openssl` package would get downgraded, but you would still likely have the `libssl3` package on your system, putting the FIPS-compliance of your system in question. But IMO we shouldn't even try to support this case as the system started in an unsupported state (non ubuntu major version of openssl installed).

**Comment by orndorffgrant** [comment]
> FWIW. Went from FIPS to FIPS-updates and got the following kernel: `5.4.0-1021-aws-fips #21+fips2-Ubuntu` After installation I rebooted to boot with the new kernel (as suggested by Pro client) and run an update/upgrade cycle. I got a new kernel: `5.4.0-1108-aws-fips #116+fips1-Ubuntu` So I had to reboot again. The question is is it possible to get installed the latest kernel when enabling FIPS-updates?

First, to clarify. If you go straight from a normal Ubuntu to FIPS-updates, then you'll go straight to the newest fips-updates kernel and only need to reboot once. This situation should only be occuring if you start on a FIPS instance, and then `pro enable fips-updates`. That is a bug, and I believe the solution proposed in comment 2 should fix it.

**Comment by carlosbravoa** [comment]
Thanks, very interesting. I just confirmed that from normal Ubuntu to fips-updates gets the latest.

**Comment by renanrodrigo** [comment]
I checked this now after a while.
There are some dependencies that are indeed not represented in the packages themselves. For instance:
- `openssl` has no relation to `openssl-fips-module-3` on Jammy
- `libgcrypt20` recommends its `hmac` variant, while other packages depend on it.

I think we can work around those details, but I will ping someone from the FIPS side to understand this better.
