### ISSUE TITLE
'permission 510'

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu-pro-client#2719]
https://github.com/canonical/ubuntu-pro-client/blob/279114c76cf6132e01d8e9393f7463678b96697d/features/attached_enable.feature#L236

Hello, I noticed a string like this repeated multiple times:

```
        Then apt-cache policy for the following url has permission `510`
```

The context suggests that this is a pin priority and not read+execute permission for the owner and execute permission for the group.

While this doesn't look like it actually influences anything, it can complicate looking for permissions problems or pinning problems in the future.

Thanks

**Comment by cpaelzer** [comment]
You are right, that should be '_permission_' -> '_priority_' in all those cases.

I always wanted to mess with those .feature files and see how bad I would break them...
