### ISSUE TITLE
Question: Trouble attaching token to machine 

### ISSUE THREAD

**Issue by Alpine-Richard** [canonical/ubuntu-pro-client#2764]
**What is the subject you need more information on?**

I have a handful of machines that cannot activate my Subscription to the machine.  These machines are Ubuntu 18.04.2 desktop running ` pro version 27.13.5~18.04.1~stableppa1` I have a proxy set up 

I have a apt-cacher-ng proxy set up for all machines in my environment I set the proxy up using the pro command for `http_proxy` `https_proxy` and `global_apt_https_proxy` but when trying to set up for `global_apt_http_proxy`. It fails with an HTTP error code 400. I can see the bad request error on the logs of the machine and on the proxy logs. 

- Not sure if this is related to my overall difficulties. 
- I can confirm that the attempt of the attachment to the token is going through the proxy 
- I have also added all the URL endpoints in [this docu](https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/references/network_requirements.html) to my allow list 
- The documentation I am going off of is [configuring proxies](https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/howtoguides/configure_proxies.html)

I will post the logs of the 18.04 machine that I am trying to attach to the Subscription but is failing. 
[logs](https://pastebin.com/2iGiLjRU)

 - [x] There is no documentation about this

**Comment by orndorffgrant** [comment]
Hi @Alpine-Richard and sorry for the delay.

First, your version of `pro` is old. Please update it to the latest, which is currently `29.4`.

Unfortunately I was too slow to see this issue and the pastebin link seems to have expired. If the newest version of `pro` still has this error, please run `sudo pro collect-logs` and attach the tarfile it creates to a comment on this issue.

**Comment by aliciousness** [comment]
27.13.5~18.04.1 is the latest stable release from your PPA UA client stable. https://launchpad.net/~ua-client/+archive/ubuntu/stable

 Is this the correct package that I should be installing? The advantage tools package that comes with the installation is out of date further and does not reflect the rebranding from ua ----> pro

**Comment by renanrodrigo** [comment]
@aliciousness hey there
`ubuntu-advantage-tools` is present in the `-updates` pocket of the release. On a 18.04 up-to-date system, the apt policy shows:
```
$ apt policy ubuntu-advantage-tools
ubuntu-advantage-tools:
  Installed: 29.4~18.04
  Candidate: 29.4~18.04
  Version table:
 *** 29.4~18.04 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     17 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

So you are correct to say that the base version (`17`) is way older, but only upgrading the package from the archive, without adding the PPA, is enough to always get the latest available version.

The `ua-client/stable` PPA is used for ad-hoc installations and to cover edge cases, where the archive version cannot be installed for some reason. That said, it *should* be up-to-date with the currently released version.  I am fixing that.

**Comment by aliciousness** [comment]
Okay I think I understand what is happening, this is not a vanilla version of 18.04. This is dell/canonical flavor of Ubuntu 18.04. I noticed that the source list for archive are labeled as such `deb http://dell.archive.canonical.com/updates/ bionic-dell-beaver-osp1-ygritte public`

I would appreciate that the ppa would be pushed to the latest version though because a lot these machines are air gapped machines as well as set up to work with the ppa

**Comment by renanrodrigo** [comment]
@aliciousness so you are part of the edge cases that need the PPA. I have uploaded everything yesterday, you should get `29.4~18.04~stableppa1` using it now.

**Comment by aliciousness** [comment]
Thanks! I appreciate it!

**Comment by renanrodrigo** [comment]
So, if updating to the latest version didn't fix the problem, then as @orndorffgrant mentioned the next steps would be `pro collect-logs` and send the resulting tarball so we can take a look.

**Comment by orndorffgrant** [comment]
@Alpine-Richard @aliciousness I'm going to go ahead and close this since we haven't heard anything. Please feel free to reopen if you're still having an issue.
