### ISSUE TITLE
Bug: attach/enable language messages is inconsistent

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-pro-client#2788]
**Description of the bug**

Not all messages use the attach/detach/enable/disable verbage and associated object consistently.

**Expected behavior**

"attach" and "detach" are verbs that act on a "subscription". "enable" and "disable" are verbs that act on a "service". All messages should use these consistently.

**Current behavior**

Some messages use "subscription" and "service(s)" interchangeably or with a verb that isn't quite right.
Examples:
```
Your Ubuntu Pro subscription has EXPIRED
Renew your service at {url}
```
The above should use "subscription" instead of "service".
```
Failed to automatically attach to Ubuntu Pro services {num_attempts}
```
The above is referring to the "attach" operation, so should use "subscription" instead of "services".

**To Reproduce**

Look through uaclient/messages/__init__.py

**System information:**

- Ubuntu release: x, b, f, f, l , m
- Pro Client version: 30

**Comment by mm-cr** [comment]
Hi, I'm Marlon. I would like to work on this issue. Could you assign it to me? Thanks!
@orndorffgrant

**Comment by orndorffgrant** [comment]
Hello @mm-cr - sure! Let me know if you have any questions
