### ISSUE TITLE
docs: Docs are inconsistent with support scope

### ISSUE THREAD

**Issue by adam-vest** [canonical/ubuntu-pro-client#2791]
*Please describe the question or issue you're facing with "Using Ubuntu Pro airgapped - Ubuntu Pro Client documentation".*

Hey there! It was discovered that the linked docs here specifically instruct folks to NOT try this task on their own, and to instead contact support for assistance:

> No matter whether you are running a truly airgapped (offline) system, or one that is heavily firewalled, running Ubuntu Pro airgapped is an advanced use-case. In both cases, you will need to contact our [Customer Support teams](https://ubuntu.com/support) who can help you implement air gapping in the best way for your specific environment.

Canonical support is bug fix/break fix support, and this would be a consultancy request. Similarly so with this statement about livepatch:

> Livepatch is the tool that provides patching for critical and high security vulnerabilities in the Ubuntu kernel. It can also be used in a firewalled setup using Livepatch on-prem, which our [Customer Support teams](https://ubuntu.com/support) can help you to set up.

Recommend we adjust the wording accordingly here.

---
*Reported from: https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/explanations/using_pro_offline.html*

**Comment by orndorffgrant** [comment]
Thanks @adam-vest! @s-makin I'll assign you to this for when you have time. After some discussion I think we want to link to the Knowledge Base how-to-guide for airgapped setup and explain that is only available to customers with paid support.

**Comment by s-makin** [comment]
Thanks for reporting the problem to us, @adam-vest 

This issue has been resolved with https://github.com/canonical/ubuntu-pro-client/pull/2893
