### ISSUE TITLE
Bug: Outdated references to ua

### ISSUE THREAD

**Issue by s-makin** [canonical/ubuntu-pro-client#2849]
**Description of the bug**

Not a bug exactly, but during my survey of the docs I discovered some places that still refer to `ua` in the code that we should look to update to `pro` if possible:

* collect logs page references the created tarfile having the name `ua_logs.tar.gz` 

If these can be updated, we will also need to update the corresponding docs pages:

* `howtoguides/how_to_collect_logs`

Edit: The following do not need to be actioned currently, as per discussion below
* security status command output references `ua` for the status of the pro client on the
`explanations/how_to_interpret_the_security_status_command` page

**Comment by renanrodrigo** [comment]
The security-status one is, unfortunately, there forever :fearful: 

No, I mean, we must keep JSON keys to assure compatibility, and this response specifically is not versioned :/
We plan to kill this for the future though - there is a plan where everything will go to the API.

**Comment by s-makin** [comment]
Perfect - thanks for the insight :) Do we need to take any action on the collect logs one, or is that also part of the API plan?

**Comment by renanrodrigo** [comment]
nono collect logs can and should be changed

**Comment by orndorffgrant** [comment]
Fixed in #2928
