### ISSUE TITLE
Bug: Livepatch/Realtime are marked as "available" on containers

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-pro-client#2854]
**Description of the bug**

When the user is unattached and runs  `pro status` on a container, he might see both `Livepatch` and `Realtime` as available, which is incorrect

**Expected behavior**

The contract server already has access to data that allows the proper analysis to verify if those services are available or not.
Once the server process that information, the Pro client will correctly show the right availability for those services 

**Current behavior**

As mentioned, those services are being incorrectly marked as available in unattached containers

**To Reproduce**

Please include details on how to reproduce the bug.
1. Launch a Jammy container
2. Run  `pro status`
3;. Verify that the services are marked as available

**System information:**

Not relevant

**Comment by orndorffgrant** [comment]
Closing this because this only requires a backend change, and not any change to the client.
