### ISSUE TITLE
Bug: fix pt_BT "fuzzy" translations

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-pro-client#2877]
Some messages have changed and require new pt_BR translations. The ones that need updating should be labeled "fuzzy".

**Comment by renanrodrigo** [comment]
I fixed fuzzy translations on the Release 31 PR - once that lands we should be good.
There should be a better way of tracking this though - as it may (will?) happen again

**Comment by renanrodrigo** [comment]
Release 31 is prepared without fuzzies
