### ISSUE TITLE
docs: proxy setup sample code fails in some setups

### ISSUE THREAD

**Issue by bernardmcginley** [canonical/ubuntu-pro-client#2881]
*Please describe the question or issue you're facing with "How to configure a proxy - Ubuntu Pro Client documentation".*

in the section detailing the sample https proxy setup command the given code fails with default proxy configs in at least some environments. I had the issue with a governmental proxy, but also with a default install of squid when trying to replicate offsite. "sudo pro config set https_proxy=https://host:port" may need to use "sudo pro config set https_proxy=http://host:port" instead to successfully connect. that's what worked in my case in both environments. might save other users some headaches if it can be referenced, even just as a footnote

---
*Reported from: https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/howtoguides/configure_proxies/*

**Comment by orndorffgrant** [comment]
Thanks for reporting this @bernardmcginley! I think we'll change the example to use `http` as you suggest. Then we'll add a note below the example explaining that you may want to use "https" depending on your proxy setup.

**Comment by s-makin** [comment]
This issue should now be resolved with https://github.com/canonical/ubuntu-pro-client/pull/3217
