### ISSUE TITLE
Feature: UACLIENT_BEHAVE_CONTRACT_SERVER=production|staging

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-pro-client#2954]
**Please describe the scenario where the new feature would be useful**

We should be able to easily point our integration tests at contracts.staging.canonical.com without editing the tests.

**Describe the solution you'd like**

UACLIENT_BEHAVE_CONTRACT_SERVER=production|staging

**Current behavior**

We need to specify in test which token to use

**Comment by renanrodrigo** [comment]
We consider this to be low priority, as it doesn't block testing, just make it annoying in some situations.

**Comment by lucasmoura** [comment]
I am closing this as we currently don't have a situation where this would be useful. If that changes in the future, let's reopen this issue
