### ISSUE TITLE
Feature: Better API for status information than status.json (and remove status.json)

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-pro-client#2967]
**Please describe the scenario where the new feature would be useful**

Other software such as desktop software needs a nice API to pro status information.

**Describe the solution you'd like**

status.json was intended to be an internal state implementation detail but now it is depended on by other software. We should create APIs that satisfy the needs of other software and then remove status.json.

**Current behavior**

status.json is depended on by other software, such as ubuntu-advantage-desktop-daemon

**Comment by lucasmoura** [comment]
We have now more APIs to show the status information. Even though they are not released yet, I am closing this now
