### ISSUE TITLE
Feature: create explicit singletons

### ISSUE THREAD

**Issue by renanrodrigo** [canonical/ubuntu-pro-client#2980]
**Please describe the scenario where the new feature would be useful**

There are some classes in the code where we need (or must have) a single instance. An explicit way of telling this would enable us to a) improve readability and expectations on such classes and b) inject the dependency on those objects in any function on any level without having to drill it down.

**Describe the solution you'd like**

A function which implements a singleton, and can be used as a decorator for the classes where we need the single instances. Then, apply this decorator to classes we identify as being singletons.

**Current behavior**

This is either done indirectly (as with the machine token, which today depends on the config, for instance) or using module level code (as with the event logger, which should go away soon, but we may have similar things around)

**Comment by dheyay** [comment]
After discussing it internally, we have decided that this is a low priority issue at the moment.
