### ISSUE TITLE
Bug: `--format yaml` doesn't generate information for machines without `--all`

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ubuntu-pro-client#2991]
**Description of the bug**

`pro status --format yaml` is supposed to be used by a machine for example. However, it doesn't generate a complete output unless `--all` is passed explicitly. By reading the help, I was under the impression that `--all` is for humans especially for the tabular output.

**Expected behavior**

`--format yaml` outputs all information out of the box.

**Current behavior**

`--format yaml` doesn't output all information unless `--all` is passed. A logic to check if a feature is enabled or not will end up with no such key in the output when trying to query `status` for name=feature.

**To Reproduce**
```
$ pro status --format yaml | wc -l
114

$ pro status --format yaml --all | wc -l
146
```

**System information:**

- Ubuntu release: VERSION="22.04.4 LTS (Jammy Jellyfish)"
- Pro Client version: 31.2~22.04

**Additional context**

**Comment by renanrodrigo** [comment]
Hello, @nobuto-m 
There are a few aspects to consider here:
1. The `--all` will only include services that are not available to a machine; thus, a script that checks for enabled services can be sure the service is disabled if it is not present in the output.
2. We are working to expose this information as an API call, as part of #2967 , and we will recommend that people move away from the `--format yaml|json` anyway
3. For the particular use case of checking enabled services, we do have the functionality implemented in the API - you can [check it here](https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/references/api/#u-pro-status-enabled-services-v1)

Closing as wontfix.

If you disagree with this decision, please reopen and add more context so we can revisit this.
