### ISSUE TITLE
Bug: failing esm-cache test on xenial only

### ISSUE THREAD

**Issue by panlinux** [canonical/ubuntu-pro-client#3013]
**Description of the bug**

This test fails consistently on xenial lxd container, in the behave suite:
```
Scenario Outline: esm cache failures don't generate errors -- @1.1 ubuntu release  # features/unattached_commands.feature:359
  Given a `xenial` `lxd-container` machine with ubuntu-advantage-tools installed   # features/steps/machines.py:167 
  When I disable access to esm.ubuntu.com                                          # features/steps/network.py:7
  And I apt update                                                                 # features/steps/packages.py:37
  When I wait `5` seconds                                                          # features/steps/misc.py:39
  And I run `systemctl --failed` with sudo                                         # features/steps/shell.py:54
  Then stdout does not match regexp                                                # features/steps/output.py:52
    """
    esm-cache\.service
    """
  When I run `journalctl -o cat -u esm-cache.service` with sudo                    # features/steps/shell.py:54
  Then stdout does not contain substring                                           # features/steps/output.py:151
    """
    raise FetchFailedException() 
    """
  Then stdout matches regexp                                                       # features/steps/output.py:129
    """
    "WARNING", "ubuntupro.apt", "fail", \d+, "Failed to fetch ESM Apt Cache item: https://esm.ubuntu.com/apps/ubuntu/dists/xenial-apps-security/InRelease", ***]
    """ 
    Assertion Failed: Expected to match regexp: 
      "WARNING", "ubuntupro.apt", "fail", \d+, "Failed to fetch ESM Apt Cache item: https://esm.ubuntu.com/apps/ubuntu/dists/xenial-apps-security/InRelease", ***]
    But got:
      Starting Update the local ESM caches... 
      Started Update the local ESM caches. 
```

I ran it locally in a lxd container, and there it passes. In other words, the system fails to reach esm.ubuntu.com, which is expected, and /etc/hosts is mangled, also as expected:
```
root@upro-behave-xenial-system-under-test-0325-185910909708:~# journalctl -o cat -u esm-cache.service
Starting Update the local ESM caches...
["2024-03-25T18:59:35.435", "WARNING", "ubuntupro.apt", "fail", 896, "Failed to fetch ESM Apt Cache item: https://esm.ubuntu.com/apps/ubuntu/dists/xenial-apps-security/InRele
["2024-03-25T18:59:35.435", "WARNING", "ubuntupro.apt", "fail", 896, "Failed to fetch ESM Apt Cache item: https://esm.ubuntu.com/apps/ubuntu/dists/xenial-apps-updates/InRelea
["2024-03-25T18:59:35.436", "WARNING", "ubuntupro.apt", "fail", 896, "Failed to fetch ESM Apt Cache item: https://esm.ubuntu.com/infra/ubuntu/dists/xenial-infra-security/InRe
["2024-03-25T18:59:35.436", "WARNING", "ubuntupro.apt", "fail", 896, "Failed to fetch ESM Apt Cache item: https://esm.ubuntu.com/infra/ubuntu/dists/xenial-infra-updates/InRel
Started Update the local ESM caches.
Starting Update the local ESM caches...
["2024-03-25T19:00:37.576", "WARNING", "ubuntupro.apt", "fail", 896, "Failed to fetch ESM Apt Cache item: https://esm.ubuntu.com/apps/ubuntu/dists/xenial-apps-security/InRele
["2024-03-25T19:00:37.576", "WARNING", "ubuntupro.apt", "fail", 896, "Failed to fetch ESM Apt Cache item: https://esm.ubuntu.com/apps/ubuntu/dists/xenial-apps-updates/InRelea
["2024-03-25T19:00:37.577", "WARNING", "ubuntupro.apt", "fail", 896, "Failed to fetch ESM Apt Cache item: https://esm.ubuntu.com/infra/ubuntu/dists/xenial-infra-security/InRe
["2024-03-25T19:00:37.577", "WARNING", "ubuntupro.apt", "fail", 896, "Failed to fetch ESM Apt Cache item: https://esm.ubuntu.com/infra/ubuntu/dists/xenial-infra-updates/InRel
Started Update the local ESM caches.
```

To troubleshoot this, we should have the following info from the container:
- `/etc/hosts`
- `env` output
- `/etc/resolv.conf`
- `/etc/nsswitch.conf`

Some speculation about this failure:
- an http proxy is at play. In that case, the DNS resolution is done by the proxy, not by the host, so changes to `/etc/hosts` meant to break the connection to esm.ubuntu.com won't work. Solution, if this is the case: set `no_proxy=esm.ubuntu.com`
- `/etc/nsswitch.conf`'s `hosts:` line could be without `files`, in which case the resolver will ignore `/etc/hosts`
- `/etc/hosts` was incorrectly mangled by the function

**Expected behavior**

The test is expected to succeed. In other words, `block_access_to_address()` is expected to block access to the site in that environment.

**Current behavior**
See description above.

**To Reproduce**

Run behave tests on xenial lxd container in github.

**System information:**

- Ubuntu release: xenial
- Pro Client version: main branch

**Additional context**

**Comment by renanrodrigo** [comment]
> Some speculation about this failure:
> - an http proxy is at play. In that case, the DNS resolution is done by the proxy, not by the host, so changes to /etc/hosts meant to break the connection to esm.ubuntu.com won't work. Solution, if this is the case: set no_proxy=esm.ubuntu.com

That does not seem to be the case. Nothing shows that - if there is a proxy, it is transparent. Maybe there is some `lxd` magic in place though... :/

> - /etc/nsswitch.conf's hosts: line could be without files, in which case the resolver will ignore /etc/hosts
All is good.

> - /etc/hosts was incorrectly mangled by the function
All is good.

**Comment by renanrodrigo** [comment]
I'd like to know how the team feels like on just documenting this fail and disabling the job on Xenial.
