### ISSUE TITLE
Question: when to run collect-logs as root?

### ISSUE THREAD

**Issue by renanrodrigo** [canonical/ubuntu-pro-client#3022]
**What is the subject you need more information on?**

Our docs guide users to run `sudo pro collect-logs`, but after we separated user logs, there are situations where the command needs to be executed as a regular user - preferrably the same user that hit the error we want to investigate.

**Did you check the documentation first?**

After looking for guidance in [the Pro Client documentation](https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/), mark one of the following checkboxes:

 - [x] There is documentation about this, but it needs improvement
 - [ ] There is no documentation about this

**Comment by orndorffgrant** [comment]
`pro collect-logs` now tries to collect all user logs it has access to, but apport needs to collect them too #3190
