### ISSUE TITLE
docs: TYPE YOUR QUESTION HERE

### ISSUE THREAD

**Issue by Alexandrer1997** [canonical/ubuntu-pro-client#3061]
*Please describe the question or issue you're facing with "How to configure a TLS-in-TLS proxy - Ubuntu Pro Client documentation".*

---
*Reported from: https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/howtoguides/configure_tls_in_tls_proxy/*

**Comment by orndorffgrant** [comment]
Hi @Alexandrer1997! Do you have a question about configuring a TLS-in-TLS proxy for `pro`?
