### ISSUE TITLE
Bug: manpage is out of date

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-pro-client#3082]
**Description of the bug**

manpage is incomplete and contains old information

**Expected behavior**

manpage should be as up-to-date as our published documentation

**Current behavior**

manpage is incomplete and out of date

**To Reproduce**

`man pro`

**System information:**

- Pro Client version: 32

**Comment by renanrodrigo** [comment]
no it's not

**Comment by renanrodrigo** [comment]
I mean we updated it recently, so this issue is fixed (:
