### ISSUE TITLE
Bug: apt news package selector list items are ANDed together instead of ORed

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-pro-client#3088]
**Description of the bug**

Given the package list:
```
          ["xorg-server", "<", "2:21.1.7-3ubuntu2.6"],
          ["xwayland", "<", "2:23.2.0-1ubuntu0.4"]
```
the news message will only be displayed if both of those packages are installed and match the version comparison.

**Expected behavior**

package comparisons should be ORed together.

**Current behavior**

They are ANDed, which makes it harder to specify messages that apply to any of several package situations

**System information:**

- Pro Client version: 32

**Comment by panlinux** [comment]
I verified spec US085, which defined apt-news package and architecture selectors, and it does define the package selector to be an "OR". I also checked that it wasn't just recently modified ;)
