### ISSUE TITLE
sudo pro config set apt_news=false not working

### ISSUE THREAD

**Issue by ldoench** [canonical/ubuntu-pro-client#3105]
I have no luck with 
`sudo pro config set apt_news=false`

`pro config show apt_news` still gives me
`apt_news True`

I have even attached a pro license to this device and enabled esm, but I still get an annoying message every time I open the cli.

---
*Reported from: https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/howtoguides/disable_enable_apt_news/?highlight=apt_news

**Comment by ldoench** [comment]
<img width="721" alt="Bildschirmfoto 2024-05-09 um 11 22 46" src="https://github.com/canonical/ubuntu-pro-client/assets/12457264/108cde6d-90a3-4977-b787-8ad63935c05f">
<img width="652" alt="Bildschirmfoto 2024-05-09 um 11 24 00" src="https://github.com/canonical/ubuntu-pro-client/assets/12457264/01728e80-ba4c-4310-9b0f-12c3beb3ccbb">

**Comment by hfdem** [comment]
I think you mean [update-motd](https://manpages.ubuntu.com/manpages/jammy/man5/update-motd.5.html).

**Comment by lucasmoura** [comment]
Yes, @hfdem is right. The MOTD message you are seeing is not related to APT news and the guide mentioned should fix your issue. I am closing this issue, but please let me know if you are still affected by this

**Comment by bghira** [comment]
this spam is pretty unprofessional tbh makes you look like some rent-starved Patreon youtubers.
