### ISSUE TITLE
Bug: doc "how auto-attach works" has invalid link to daemon

### ISSUE THREAD

**Issue by pandrey2003** [canonical/ubuntu-pro-client#3180]
**Description of the bug**

Open the "how auto-attach works" [doc](https://github.com/canonical/ubuntu-pro-client/blob/docs/dev-docs/explanations/how_auto_attach_works.md) and click on the "daemon" link.

**Expected behavior**

The document on what is a daemon opened.

**Current behavior**

The GitHub Web UI says "page not found".

**Comment by orndorffgrant** [comment]
Thanks for finding this!

**Comment by orndorffgrant** [comment]
Fixed in the referenced commit: https://github.com/canonical/ubuntu-pro-client/commit/9021ca757fe73f4f1d2137ab82ede87c9a005247
