### ISSUE TITLE
docs: After messy upgrade from 22.04 to 24.04, I'm not sure if pro is correctly installed

### ISSUE THREAD

**Issue by trancephorm** [canonical/ubuntu-pro-client#3207]
I made lot of manual changes to sources.list to make 24.04 fully functional after upgrade and I noticed https://esm.ubuntu.com is now missing, I actually don't think I'm receiving pro updates.

Is there any way I can check if everything is alright?

---
*Reported from: https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/howtoguides/how_to_simulate_attach/*

**Comment by orndorffgrant** [comment]
Hi @trancephorm thanks for the question.

Generally `sudo pro status` should tell you if esm-infra and esm-apps are enabled or not. If you want to check the config files you will find them here:
```
root@test:~# ls /etc/apt/sources.list.d/
ubuntu-esm-apps.sources  ubuntu-esm-infra.sources  ubuntu.sources
root@test:~# ls /etc/apt/auth.conf.d/
90ubuntu-advantage
```

You can also verify that `apt` is seeing available updates by checking the policy of a package that should have an ESM update available. `hello` is a package that has an example ESM update available:

```
root@test:~# apt policy hello
hello:
  Installed: (none)
  Candidate: 2.10-3build1.1~esm1
  Version table:
     2.10-3build1.1~esm1 510
        510 https://esm.ubuntu.com/apps/ubuntu noble-apps-security/main amd64 Packages
        510 https://esm.ubuntu.com/infra/ubuntu noble-infra-security/main amd64 Packages
        510 https://esm.ubuntu.com/infra/ubuntu noble-infra-updates/main amd64 Packages
     2.10-3build1 500
        500 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages
     2.10-3build1~esm1 510
        510 https://esm.ubuntu.com/apps/ubuntu noble-apps-updates/main amd64 Packages
```

**Comment by trancephorm** [comment]
Thank you for your reply. I am missing those files in /etc/apt/sources.list.d/

sudo pro status looks like this:
`SERVICE          ENTITLED  STATUS       DESCRIPTION
anbox-cloud      yes       disabled     Scalable Android in the cloud
esm-apps         yes       disabled     Expanded Security Maintenance for Applications
esm-infra        yes       disabled     Expanded Security Maintenance for Infrastructure
livepatch        yes       enabled      Canonical Livepatch service
realtime-kernel* yes       disabled     Ubuntu kernel with PREEMPT_RT patches integrated
`
apt policy hello
`hello:
  Installed: (none)
  Candidate: 2.10-3build1
  Version table:
     2.10-3build1 500
        500 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages
`

Can you help me on how this can be fixed? Thank you very much!

**Comment by orndorffgrant** [comment]
Hi @trancephorm please try `sudo pro enable esm-infra esm-apps`

**Comment by trancephorm** [comment]
Worked, thank you!!

**Comment by orndorffgrant** [comment]
@trancephorm Great! Glad to help
