### ISSUE TITLE
Bug: apt_news download forced unsandboxed

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-pro-client#3209]
**Description of the bug**
On Noble, when triggering the apt_news job, we can see this warning on `/var/log/syslog`:

```
Warning: W:Download is performed unsandboxed as root as file '/run/ubuntu-advantage/aptnews.json' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

**Expected behavior**
We shouldn't see this warning in syslog

**To Reproduce**

1. Launch a Noble VM
2. Run apt update and wait a couple of seconds to guarantee that the apt news service was executed
3. Look at `/var/log/syslog` to see the warning is there

**System information:**

- Ubuntu release: Noble
- Pro Client version: 32.3.1

**Additional context**

This bug was originally reported on [launchpad](https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/2070095)

**Comment by orndorffgrant** [comment]
Andreas triaged this over on LP, quoting him here:

> Yeah, so Pro is using apt_pkg.Acquire() to download the aptnews json file and store it in /run/ubuntu-advantage, where only root can write to. It tries to do that as an unprivileged user first ("_apt"), and if that fails, it switches to root and issues that warning.
>
> There are multiple ways to fix this, including:
> - store the file in memory first, and then have pro write it out at that location
> - download it elsewhere (/tmp? Or another directory under /run/ubuntu-advantage where _apt can write to?), and then move it over to /run/ubuntu-advantage
> - ignore the warning? less desirable, because it's actually a nice security feature to download the file as non-root.

**Comment by orndorffgrant** [comment]
I'm not sure what the implications of having a file writable by user `_apt` are, though. Is that equivalent or different from being world-writable?

**Comment by orndorffgrant** [comment]
I would prefer to read it into memory and not write the file in /run at all, but apt_pkg doesn't have a convenient interface for that IIRC.

**Comment by panlinux** [comment]
Maybe @julian-klode has a nice suggestion?
