### ISSUE TITLE
Bug: Trying to enable landscape says it's not available for releases older than Noble

### ISSUE THREAD

**Issue by renanrodrigo** [canonical/ubuntu-pro-client#3331]
**Description of the bug**

Landscape is available for all supported releases, but it was only defined as a pro service from 23.10 (mantic).
This means that trying to enable Landscape using Pro works fine on Noble, for instance, but on other releases it gives misleading information, telling the user that Landscape is not available to the specific release.

We need to implement better communication, informing users that Landscape is actually available, just not through Pro.

**Expected behavior**

```
$ sudo pro enable landscape
Landscape cannot be enabled via Pro Client on Ubuntu 22.04 and earlier.
Please manually install Landscape: https://ubuntu.com/landscape/install
```

**Current behavior**

```
$ sudo pro enable landscape
Landscape is not available for Ubuntu 22.04 LTS (Jammy Jellyfish).
```

**To Reproduce**

1. Launch a Focal/Jammy VM/Container
2. Attach to a subscription
3. Try to enable Landscape

**System information:**

- Ubuntu release: xenial(?), bionic(?), focal, jammy
- Pro Client version: 34

**Comment by orndorffgrant** [comment]
We need to verify which releases we put the new message on (do we include xenial?)

Also https://ubuntu.com/landscape/install is a confusing landing page for installing the client, I'll reach out to landscape for a better link
