### ISSUE TITLE
v1/resources endpoint may require new parameter to describe is_container

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#831]
Since v1/resources needs to express whether a service is available to unattached machines, it should not falsely report "yes" for livepatch or fips if the machine in question is running in a container because those services will never be available to containers.

See  https://github.com/CanonicalLtd/ua-contracts/issues/469  resolution once it lands for an understanding of how UA Client can support this.

**Comment by powersj** [comment]
Will keep in 19.5.1 for now, but if backend does not accept the idea then we will push to a future release.

**Comment by powersj** [comment]
Bumping to 19.6

**Comment by orndorffgrant** [comment]
Bumped server-side bug thread and tracking in SC-1126

**Comment by lucasmoura** [comment]
@orndorffgrant I think we are already covering this by sending the information we collect from `systemd-detect-virt`.
Even though the CS is not still properly evaluating that field, the work on our side is done. Should we close this issue ?

**Comment by orndorffgrant** [comment]
@lucasmoura I'm okay closing this one if we open a new one more specifically for unattached status saying livepatch/realtime are available even on containers

**Comment by lucasmoura** [comment]
@orndorffgrant done
https://github.com/canonical/ubuntu-pro-client/issues/2854
